### ISSUE TITLE
ant fails because bin is missing

### ISSUE THREAD

**Issue by rlaemmel** [softlang/megalib#1]
/cc @AndrEm12 @MarcelH91 

See error below.
Apparently bin is not needed in the end, but one has to create it manually to push through ant-based build.

<pre>
$ ant
Buildfile: /Users/laemmel/github/softlang/megalib/checker/build.xml

create_run_jar:

BUILD FAILED
/Users/laemmel/github/softlang/megalib/checker/build.xml:9: /Users/laemmel/github/softlang/megalib/checker/bin does not exist.
</pre>

**Comment by dblM90** [comment]
we will use maven in the future
