### ISSUE TITLE
Build with maven fails

### ISSUE THREAD

**Issue by nikonovd** [softlang/megalib#10]
I recently checked out the repository to build the checker project with netbeans and maven (Netbeans 8.2, JDK 1.8, Linux Mint 18.1). Unfortunately the build fails with test failure. The surefire test reports are attached to this issue below.

- [org.java.megalib.checker.services.CheckTest.txt](https://github.com/softlang/megalib/files/739205/org.java.megalib.checker.services.CheckTest.txt)
- [org.java.megalib.checker.services.ImportTest.txt](https://github.com/softlang/megalib/files/739206/org.java.megalib.checker.services.ImportTest.txt)
- [org.java.megalib.checker.services.SubstitutionTest.txt](https://github.com/softlang/megalib/files/739207/org.java.megalib.checker.services.SubstitutionTest.txt)
- [org.java.megalib.parser.ParserListenerTest.txt](https://github.com/softlang/megalib/files/739208/org.java.megalib.parser.ParserListenerTest.txt)

**Comment by MarcelH91** [comment]
Just don't try to build it yourself for now and use the uploaded .jar file instead. I'm working on some syntactic changes that are hopefully finished by tomorrow and then the build will work again as well.

**Comment by MarcelH91** [comment]
Look here for instructions: https://github.com/softlang/megalib/wiki/How-to-load-a-model

**Comment by MarcelH91** [comment]
Build does not fail anymore
