### ISSUE TITLE
installation, build, test, run info not there

### ISSUE THREAD

**Issue by rlaemmel** [softlang/megalib#12]
When landing on the github repo, there is some README.md, but it does not answer the standard questions that users may be have, as listed in the title of the issue.

**Comment by MarcelH91** [comment]
Addressed it more explicitly here: https://github.com/softlang/megalib/wiki

**Comment by rlaemmel** [comment]
The thing is I don't know that there is a wiki, I will not find it.
So maybe this can be fixed by linking from the README
or making the web presence by other means very discoverable.

**Comment by MarcelH91** [comment]
At least it is in the Readme now. Now idea right now how to otherwise make this more discoverable...
