### ISSUE TITLE
Shell freezing after checker excecution

### ISSUE THREAD

**Issue by mmonschau** [softlang/megalib#15]
After executing the checker in my terminal emulator every now and then the my shell freezes and refuses any further input.

Java:
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
Terminal Emulator:
xfce4-terminal 0.8.6
Shell:
zsh 5.4.2 (x86_64-debian-linux-gnu)
with grml-config

**Comment by MarcelH91** [comment]
Can you tell whether the JVM is stopped, when the shell freezes?

**Comment by MarcelH91** [comment]
Now, I'm working a lot with a MAC. Thus, the described problem should not be caused by megalib's tools. I cannot reproduce the issue.
