### ISSUE TITLE
There should be presumably a  test target for ant

### ISSUE THREAD

**Issue by rlaemmel** [softlang/megalib#2]
/cc @AndrEm12 @MarcelH91 

... so that one can simply run the checker on the TestFiles.

Proper examples should be in directory models, btw, but I think it is Ok to have developer-level tests separately, as you do.

**Comment by rlaemmel** [comment]
The test target should also "test" the models in directory "models".

So the assumption here is that:
- the files in TestFiles are for development testing and covers positive and negative tests.
- the files in models constitute the actual library and these are essentially positive tests.

**Comment by dblM90** [comment]
see issue #1
