### ISSUE TITLE
There should be a .zip file for end users

### ISSUE THREAD

**Issue by rlaemmel** [softlang/megalib#3]
/cc @AndrEm12 @MarcelH91 

which should contain:
- JARs
- Scripts
- README to explain how to run the tool
- the contents of directory models

This is how we would release the the tool.

So I guess the build.xml file could have a release target which build the .zip file.

We could then upload the zip to somewhere.

**Comment by dblM90** [comment]
we will use the release feature of github. the zip will be generated on a loacl machine and uploaded to github
