### ISSUE TITLE
Ant build is vacuously successful

### ISSUE THREAD

**Issue by rlaemmel** [softlang/megalib#4]
/cc @AndrEm12 @MarcelH91 

Ant seems to complete build fine; see below.
... but ANTLR is not invoked and obviously there must be Java errors.
No Java errors reach the console.

So make sure to avoid having vacuous success.
Also, make sure the build actually completes successfully.

<pre>
 ant
Buildfile: /Users/laemmel/github/softlang/megalib/checker/build.xml

create_run_jar:

BUILD SUCCESSFUL
Total time: 0 seconds
</pre>

**Comment by MarcelH91** [comment]
In CheckerTests.java, I also see this
<pre>
import static org.hamcrest.CoreMatchers.instanceOf;
import static org.junit.Assert.assertThat;
</pre>

Hamcrest and JUnit are both not in the build path after building with your ANT script build.xml.

**Comment by dblM90** [comment]
see #1
